apiVersion: apps/v1beta1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: aws-costs-adapter-v1
spec:
  selector:
    matchLabels:
      app: aws-costs-adapter-v1
  replicas: 1
  template:
    metadata:
      labels:
        app: aws-costs-adapter-v1
    spec:
      containers:
      - name: aws-costs-adapter-v1
        image: consortit-docker-cme-local.jfrog.io/aws-costs-adapter:image-version
        ports:
        - containerPort: 8081
        - containerPort: 8080
        env:
        - name: jwk_url
          value: "https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_M4FyC0JPA/.well-known/jwks.json"
        - name: jwk_alg
          value: "RS256"
        - name: jwk_kid
          valueFrom:
            secretKeyRef:
              name: aws-costs-adapter-secret
              key: jwk_kid
        - name: ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-costs-adapter-secret
              key: accesskey
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: aws-costs-adapter-secret
              key: secretkey
      imagePullSecrets:
        - name: regsecret

---
apiVersion: v1
kind: Service
metadata:
  name: aws-costs-adapter-v1
  labels:
    app: aws-costs-adapter-v1
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: external
    - port: 81
      protocol: TCP
      targetPort: 8081
      name: external2
  selector:
    app: aws-costs-adapter-v1

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: aws-costs-adapter-v1
  labels:
    app: aws-costs-adapter-v1
spec:
  rules:
  - host: "cme.dev.k8s.consort-it.de"
    http:
      paths:
      - path: /api/v1/aws-costs-adapter
        backend:
          serviceName: "aws-costs-adapter-v1"
          servicePort: 80
      - path: /api/v1/aws-costs-adapter/health
        backend:
          serviceName: "aws-costs-adapter-v1"
          servicePort: 81
      - path: /api/v1/aws-costs-adapter/metrics
        backend:
          serviceName: "aws-costs-adapter-v1"
          servicePort: 81